INSERT INTO province(id,name) VALUES(1,'BUENOS AIRES');
INSERT INTO province(id,name) VALUES(2,'CATAMARCA');
INSERT INTO province(id,name) VALUES(3,'CHACO');
INSERT INTO province(id,name) VALUES(4,'CHUBUT');
INSERT INTO province(id,name) VALUES(5,'CORDOBA');
INSERT INTO province(id,name) VALUES(6,'CORRIENTES');
INSERT INTO province(id,name) VALUES(7,'ENTRE RIOS');
INSERT INTO province(id,name) VALUES(8,'FORMOSA');
INSERT INTO province(id,name) VALUES(9,'JUJUY');
INSERT INTO province(id,name) VALUES(10,'LA PAMPA');
INSERT INTO province(id,name) VALUES(11,'LA RIOJA');
INSERT INTO province(id,name) VALUES(12,'MENDOZA');
INSERT INTO province(id,name) VALUES(13,'MISIONES');
INSERT INTO province(id,name) VALUES(14,'NEUQUEN');
INSERT INTO province(id,name) VALUES(15,'RIO NEGRO');
INSERT INTO province(id,name) VALUES(16,'SALTA');
INSERT INTO province(id,name) VALUES(17,'SAN JUAN');
INSERT INTO province(id,name) VALUES(18,'SAN LUIS');
INSERT INTO province(id,name) VALUES(19,'SANTA CRUZ');
INSERT INTO province(id,name) VALUES(20,'SANTA FE');
INSERT INTO province(id,name) VALUES(21,'SANTIAGO DEL ESTERO');
INSERT INTO province(id,name) VALUES(22,'TIERRA DEL FUEGO');
INSERT INTO province(id,name) VALUES(23,'TUCUMAN');
INSERT INTO city(id,province_id,name) VALUES(1,1,'AZUL');
INSERT INTO city(id,province_id,name) VALUES(2,1,'PUAN');
INSERT INTO city(id,province_id,name) VALUES(3,1,'LA MATANZA');
INSERT INTO city(id,province_id,name) VALUES(4,1,'TIGRE');
INSERT INTO city(id,province_id,name) VALUES(5,1,'25 DE MAYO');
INSERT INTO city(id,province_id,name) VALUES(6,1,'TRENQUE LAUQUEN');
INSERT INTO city(id,province_id,name) VALUES(7,1,'9 DE JULIO');
INSERT INTO city(id,province_id,name) VALUES(8,1,'LANUS');
INSERT INTO city(id,province_id,name) VALUES(9,1,'LA PLATA');
INSERT INTO city(id,province_id,name) VALUES(10,1,'MONTE');
INSERT INTO city(id,province_id,name) VALUES(11,1,'PEHUAJO');
INSERT INTO city(id,province_id,name) VALUES(12,1,'SAN ISIDRO');
INSERT INTO city(id,province_id,name) VALUES(13,1,'PERGAMINO');
INSERT INTO city(id,province_id,name) VALUES(14,1,'ALBERTI');
INSERT INTO city(id,province_id,name) VALUES(15,1,'CHASCOMUS');
INSERT INTO city(id,province_id,name) VALUES(16,1,'ESTEBAN ECHEVERRIA');
INSERT INTO city(id,province_id,name) VALUES(17,1,'MERCEDES');
INSERT INTO city(id,province_id,name) VALUES(18,1,'BAHIA BLANCA');
INSERT INTO city(id,province_id,name) VALUES(19,1,'MERLO');
INSERT INTO city(id,province_id,name) VALUES(20,1,'JUNIN');
INSERT INTO city(id,province_id,name) VALUES(21,1,'GUAMINI');
INSERT INTO city(id,province_id,name) VALUES(22,1,'LUJAN');
INSERT INTO city(id,province_id,name) VALUES(23,1,'LEANDRO N.ALEM');
INSERT INTO city(id,province_id,name) VALUES(24,1,'MATANZA');
INSERT INTO city(id,province_id,name) VALUES(25,1,'GENERAL PAZ');
INSERT INTO city(id,province_id,name) VALUES(26,1,'SAN VICENTE');
INSERT INTO city(id,province_id,name) VALUES(27,1,'CAÑUELAS');
INSERT INTO city(id,province_id,name) VALUES(28,1,'ALMIRANTE BROWN');
INSERT INTO city(id,province_id,name) VALUES(29,1,'CNL.DE MARINA  L.ROSALES');
INSERT INTO city(id,province_id,name) VALUES(30,1,'BARADERO');
INSERT INTO city(id,province_id,name) VALUES(31,1,'SAAVEDRA');
INSERT INTO city(id,province_id,name) VALUES(32,1,'BRANDSEN');
INSERT INTO city(id,province_id,name) VALUES(33,1,'GENERAL SARMIENTO');
INSERT INTO city(id,province_id,name) VALUES(34,1,'TAPALQUE');
INSERT INTO city(id,province_id,name) VALUES(35,1,'SALADILLO');
INSERT INTO city(id,province_id,name) VALUES(36,1,'MAGDALENA');
INSERT INTO city(id,province_id,name) VALUES(37,1,'GONZALES CHAVES');
INSERT INTO city(id,province_id,name) VALUES(38,1,'GENERAL PINTO');
INSERT INTO city(id,province_id,name) VALUES(39,1,'NAVARRO');
INSERT INTO city(id,province_id,name) VALUES(40,1,'DAIREAUX');
INSERT INTO city(id,province_id,name) VALUES(41,1,'LOBOS');
INSERT INTO city(id,province_id,name) VALUES(42,1,'CORONEL DORREGO');
INSERT INTO city(id,province_id,name) VALUES(43,1,'ADOLFO ALSINA');
INSERT INTO city(id,province_id,name) VALUES(44,1,'COLON');
INSERT INTO city(id,province_id,name) VALUES(45,1,'GENERAL ARENALES');
INSERT INTO city(id,province_id,name) VALUES(46,1,'LINCOLN');
INSERT INTO city(id,province_id,name) VALUES(47,1,'VILLARINO');
INSERT INTO city(id,province_id,name) VALUES(48,1,'VICENTE LOPEZ');
INSERT INTO city(id,province_id,name) VALUES(49,1,'BARTOLOME MITRE');
INSERT INTO city(id,province_id,name) VALUES(50,1,'EXALTACION DE LA CRUZ');
INSERT INTO city(id,province_id,name) VALUES(51,1,'SALTO');
INSERT INTO city(id,province_id,name) VALUES(52,1,'BRAGADO');
INSERT INTO city(id,province_id,name) VALUES(53,1,'ZARATE');
INSERT INTO city(id,province_id,name) VALUES(54,1,'AVELLANEDA');
INSERT INTO city(id,province_id,name) VALUES(55,1,'AYACUCHO');
INSERT INTO city(id,province_id,name) VALUES(56,1,'SAN ANDRES DE GILES');
INSERT INTO city(id,province_id,name) VALUES(57,1,'TANDIL');
INSERT INTO city(id,province_id,name) VALUES(58,1,'RIVADAVIA');
INSERT INTO city(id,province_id,name) VALUES(59,1,'PATAGONES');
INSERT INTO city(id,province_id,name) VALUES(60,1,'GRL.VIAMONTE');
INSERT INTO city(id,province_id,name) VALUES(61,1,'CNL.DE MARINA LEONARDO ROSALES');
INSERT INTO city(id,province_id,name) VALUES(62,1,'BALCARCE');
INSERT INTO city(id,province_id,name) VALUES(63,1,'TRES ARROYOS');
INSERT INTO city(id,province_id,name) VALUES(64,1,'GENERAL VILLEGAS');
INSERT INTO city(id,province_id,name) VALUES(65,1,'LOMAS DE ZAMORA');
INSERT INTO city(id,province_id,name) VALUES(66,1,'BERISSO');
INSERT INTO city(id,province_id,name) VALUES(67,1,'JUAREZ');
INSERT INTO city(id,province_id,name) VALUES(68,1,'GRL.PUEYRREDON');
INSERT INTO city(id,province_id,name) VALUES(69,1,'CORONEL SUAREZ');
INSERT INTO city(id,province_id,name) VALUES(70,1,'ESCOBAR');
INSERT INTO city(id,province_id,name) VALUES(71,1,'CARLOS CASARES');
INSERT INTO city(id,province_id,name) VALUES(72,1,'CHIVILCOY');
INSERT INTO city(id,province_id,name) VALUES(73,1,'BERAZATEGUI');
INSERT INTO city(id,province_id,name) VALUES(74,1,'QUILMES');
INSERT INTO city(id,province_id,name) VALUES(75,1,'TORQUINST');
INSERT INTO city(id,province_id,name) VALUES(76,1,'3 DE FEBRERO');
INSERT INTO city(id,province_id,name) VALUES(77,1,'OLAVARRIA');
INSERT INTO city(id,province_id,name) VALUES(78,1,'PELLEGRINI');
INSERT INTO city(id,province_id,name) VALUES(79,1,'GENERAL BELGANO');
INSERT INTO city(id,province_id,name) VALUES(80,1,'FLORENCIO VARELA');
INSERT INTO city(id,province_id,name) VALUES(81,1,'SALLIQUELO');
INSERT INTO city(id,province_id,name) VALUES(82,1,'CNL.DE MARINA L.ROSALES');
INSERT INTO city(id,province_id,name) VALUES(83,1,'MAR CHIQUITA');
INSERT INTO city(id,province_id,name) VALUES(84,1,'GENERAL PUEYRREDON');
INSERT INTO city(id,province_id,name) VALUES(85,1,'CAMPANA');
INSERT INTO city(id,province_id,name) VALUES(86,1,'GRL.SARMIENTO');
INSERT INTO city(id,province_id,name) VALUES(87,1,'ROJAS');
INSERT INTO city(id,province_id,name) VALUES(88,1,'SARMIENTO');
INSERT INTO city(id,province_id,name) VALUES(89,1,'CARMEN DE ARECO');
INSERT INTO city(id,province_id,name) VALUES(90,1,'PILA');
INSERT INTO city(id,province_id,name) VALUES(91,1,'TRES DE FEBRERO');
INSERT INTO city(id,province_id,name) VALUES(92,1,'MORON');
INSERT INTO city(id,province_id,name) VALUES(93,1,'CASTELLI');
INSERT INTO city(id,province_id,name) VALUES(94,1,'CHACABUCO');
INSERT INTO city(id,province_id,name) VALUES(95,1,'GENERAL VIAMONTE');
INSERT INTO city(id,province_id,name) VALUES(96,1,'RAUCH');
INSERT INTO city(id,province_id,name) VALUES(97,1,'GENERAL BELGRANO');
INSERT INTO city(id,province_id,name) VALUES(98,1,'TORNQUIST');
INSERT INTO city(id,province_id,name) VALUES(99,1,'NECOCHEA');
INSERT INTO city(id,province_id,name) VALUES(100,1,'MARCOS PAZ');
INSERT INTO city(id,province_id,name) VALUES(101,1,'CARLOS TEJEDOR');
INSERT INTO city(id,province_id,name) VALUES(102,1,'SAN PEDRO');
INSERT INTO city(id,province_id,name) VALUES(103,1,'GENERAL ALVARADO');
INSERT INTO city(id,province_id,name) VALUES(104,1,'SAN NICOLAS');
INSERT INTO city(id,province_id,name) VALUES(105,1,'HIPOLITO YRIGOYEN');
INSERT INTO city(id,province_id,name) VALUES(106,1,'LAS FLORES');
INSERT INTO city(id,province_id,name) VALUES(107,1,'CORONEL PRINGLES');
INSERT INTO city(id,province_id,name) VALUES(108,1,'GENERAL SAN MARTIN');
INSERT INTO city(id,province_id,name) VALUES(109,1,'BENITO JUAREZ');
INSERT INTO city(id,province_id,name) VALUES(110,1,'SAN CAYETANO');
INSERT INTO city(id,province_id,name) VALUES(111,1,'ADOLFO GONZALES CHAVES');
INSERT INTO city(id,province_id,name) VALUES(112,1,'DOLORES');
INSERT INTO city(id,province_id,name) VALUES(113,1,'SAN ANTONIO');
INSERT INTO city(id,province_id,name) VALUES(114,1,'LOBERIA');
INSERT INTO city(id,province_id,name) VALUES(115,1,'RAMALLO');
INSERT INTO city(id,province_id,name) VALUES(116,1,'GENERAL ALVEAR');
INSERT INTO city(id,province_id,name) VALUES(117,1,'ENSENADA');
INSERT INTO city(id,province_id,name) VALUES(118,1,'TORDILLO');
INSERT INTO city(id,province_id,name) VALUES(119,1,'GENERAL GUIDO');
INSERT INTO city(id,province_id,name) VALUES(120,1,'GENERAL LAS HERAS');
INSERT INTO city(id,province_id,name) VALUES(121,1,'GENERAL JUAN MADARIAGA');
INSERT INTO city(id,province_id,name) VALUES(122,1,'GENERAL LA MADRID');
INSERT INTO city(id,province_id,name) VALUES(123,1,'GENERAL LAVALLE');
INSERT INTO city(id,province_id,name) VALUES(124,1,'GENERAL RODRIGUEZ');
INSERT INTO city(id,province_id,name) VALUES(125,1,'GENERAL VLLEGAS');
INSERT INTO city(id,province_id,name) VALUES(126,1,'ADOLFO GONZALEZ CHAVES');
INSERT INTO city(id,province_id,name) VALUES(127,1,'CORONEL DE MARINA L.ROSALES');
INSERT INTO city(id,province_id,name) VALUES(128,1,'BOLIVAR');
INSERT INTO city(id,province_id,name) VALUES(129,1,'SAN FERNANDO');
INSERT INTO city(id,province_id,name) VALUES(130,1,'CAPITAN SARMIENTO');
INSERT INTO city(id,province_id,name) VALUES(131,1,'ROQUE PEREZ');
INSERT INTO city(id,province_id,name) VALUES(132,1,'MORENO');
INSERT INTO city(id,province_id,name) VALUES(133,1,'LAPRIDA');
INSERT INTO city(id,province_id,name) VALUES(134,1,'MAIPU');
INSERT INTO city(id,province_id,name) VALUES(135,1,'ECHEVERRIA');
INSERT INTO city(id,province_id,name) VALUES(136,1,'PILAR');
INSERT INTO city(id,province_id,name) VALUES(137,1,'CORONEL DE MARINA L. ROSALES');
INSERT INTO city(id,province_id,name) VALUES(138,1,'SUIPACHA');
INSERT INTO city(id,province_id,name) VALUES(139,1,'SAN ANTONIO DE ARECO');
INSERT INTO city(id,province_id,name) VALUES(140,1,'BARAZATEGUI');
INSERT INTO city(id,province_id,name) VALUES(141,1,'ALSINA');
INSERT INTO city(id,province_id,name) VALUES(142,1,'LEANDRO N. ELEM');
INSERT INTO city(id,province_id,name) VALUES(143,1,'GRL.SAN MARTIN');
